version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - mynetwork
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - '9000:9000'
    networks:
      - mynetwork
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb 
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - '443:443'
    networks:
      - mynetwork
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env

networks:
  mynetwork:
    name: My-net
    driver: bridge

volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      device: /home/majmani/data/mariadb
      o: bind
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      device: /home/majmani/data/wordpress
      o: bind

