version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: /home/majmani/Desktop/inception/mariadb
    networks:
      - mynetwork
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    image: wordpress
    container_name: word
    build: /home/majmani/Desktop/inception/wordpress
    ports:
      - '9000:9000'
    networks:
      - mynetwork
    volumes:
      - data2:/var/www/html
    depends_on:
      - mariadb 
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: nginx
    build: /home/majmani/Desktop/inception/nginx
    ports:
      - '443:443'
    networks:
      - mynetwork
    volumes:
      - data2:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env

networks:
  mynetwork:
    name: My-net
    driver: bridge

volumes:
  data:
    name: data
  data2:
    name: data2
